In [2]:
import numpy as np
import pandas as pd


### creating a array using numpy

In [3]:
arr = np.array([[1,3,6],[4,5,2]])
print(arr)

[[1 3 6]
 [4 5 2]]


In [8]:
# np array() functions 
# ndim : Returns number of dimensions.

# shape: Returns Shape in tuple.

# size : Total number of elements.

# dtype : Type of each element.

# itemsize : Size of each element in Bytes.

# nbytes : Total bytes consumed by all elements.

# Example 3

print(arr.ndim, arr.shape, arr.size, arr.dtype, arr.itemsize, arr.nbytes)

2 (2, 3) 6 int32 4 24


In [25]:
a = np.array([[[1,2],[4,2],[2,1]]])
print(a.shape)
print(a)
a.transpose()


(1, 3, 2)
[[[1 2]
  [4 2]
  [2 1]]]


array([[[1],
        [4],
        [2]],

       [[2],
        [2],
        [1]]])

In [23]:
b = np.arange(1,13)
b.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

###### creating array with zeros, ones, fill and empty functions


In [45]:
arr = np.zeros((2,4),dtype="int")
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
arr = np.ones((3,2,4),dtype="str")
arr

array([[['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1']]], dtype='<U1')

In [48]:
# ones_like and zeros_like
arr=np.ones_like(arr)
#arr = np.zeros_like(["2","4","3"]) #if given a string array will return only array(['', '', ''], dtype='<U1')
arr

array(['1', '1', '1'], dtype='<U1')

In [53]:
# np.fill and  np.full 
arr = np.arange(2,9) #[2 3 4 5 6 7 8]
print(arr)
arr.fill(5) #[5 5 5 5 5 5 5]
print(arr)

np.full(shape=(3,4),fill_value=9)

[2 3 4 5 6 7 8]
[5 5 5 5 5 5 5]


array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [62]:
# np.empty and np.eye
arr = np.empty((3,4))
print(arr)

# eye fun returns the array filled with zeros except for the diagonal k value represents the filled diagonal
# syntax => np.eye(row,col,k=0,dtype=float) k can take values 1,0,-1 for upper main and lower diagonal respectively
arr = np.eye(5,4,k=1)
print(arr)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


###### arange, linspace, reshape, flatten and ravel functions

In [65]:
#arange vs linspace 

# arange --> np.arange(start, stop, step, …)
# start: The starting value of the sequence
# stop: The end value of the sequence
# step: The spacing between values
#create sequence of values between 0 and 20 where spacing is 2
arr = np.arange(0, 20, 2)
print(arr)

# linspace --> np.linspace(start, stop, num, …)
# start: The starting value of the sequence
# stop: The end value of the sequence
# num: the number of values to generate

#create sequence of 5 evenly spaced values between 2 and 8
arr = np.linspace(2,8,5)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]
[2.  3.5 5.  6.5 8. ]


In [70]:
# reshape 
#syntax --> numpy.reshape(array, shape, order = 'C')
arr = np.arange(0,10)
print(arr.reshape(2,5))

arr = np.linspace(1,50,10).reshape(5,2)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1.          6.44444444]
 [11.88888889 17.33333333]
 [22.77777778 28.22222222]
 [33.66666667 39.11111111]
 [44.55555556 50.        ]]


In [80]:
#flatten and ravel 
#flatten
arr = np.ones((3,2,4))
print(arr)
print(arr.flatten())

#ravelf
arr=np.arange(10).reshape(2,5)
print(arr)
arr.ravel()

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Difference between ravel and flatten**
<table>
    <thead>
    <th>Ravel</th>
    <th>flatten</th>
    </thead>
    <tbody>
        <tr>
            <td>Return only reference/view of the original array</td>
            <td>Return copy of the original array</td>
        </tr>
          <tr>
            <td>If you modify the array you would notice that the value of the original array also changes.</td>
            <td>If you modify any value of this array value of the original array is not affected.</td>
        </tr>
         <tr>
            <td>Ravel is faster than flatten() as it does not occupy any memory.</td>
            <td>Flatten() is comparatively slower than ravel() as it occupies memory</td>
        </tr>
         <tr>
            <td>Ravel is a library-level function. </td>
            <td>	Flatten is a method of an ndarray object. Let us check out the difference in this code.</td>
        </tr>
    </tbody>
    
</table>


### Array Slicing 

In [102]:
arr = np.arange(50).reshape(10,5)
print(arr)
print("\n")
print("array ate index 4\n",arr[4])
print("\narray index [3,4] -",arr[3,4])
print("\nslice arr[2:4] -\n",arr[2:4]) # will print till [m:n-1]
print("\n slice arr[2:5,1:4]\n", arr[2:5,1:4])
print("\n slice arr[3:6,3]\n", arr[3:6,2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


array ate index 4
 [20 21 22 23 24]

array index [3,4] - 19

slice arr[2:4] -
 [[10 11 12 13 14]
 [15 16 17 18 19]]

 slice arr[2:5,1:4]
 [[11 12 13]
 [16 17 18]
 [21 22 23]]

 slice arr[3:6,3]
 [17 22 27]


#### Basic Numpy operations on arrays

* Note : all operations performed (+,-,*,/,%,etc) are element wise operations 


In [114]:
a = np.arange(6).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

print(a,"\n",b)
print()
print(" a+b\n",a+b) #or np.add(a,b)

# similary we can perform
print(" a-b \n",a-b) #or np.substract(a,b)
print(" a*b\n",a*b) #or np.multipy(a,b)
print(" a/b\n",a/b) #or np.divide(a,b)
print(" a%b \n",a%b)

[[0 1 2]
 [3 4 5]] 
 [[ 7  8  9]
 [10 11 12]]

 a+b
 [[ 7  9 11]
 [13 15 17]]
 a-b 
 [[-7 -7 -7]
 [-7 -7 -7]]
 a*b
 [[ 0  8 18]
 [30 44 60]]
 a/b
 [[0.         0.125      0.22222222]
 [0.3        0.36363636 0.41666667]]
 a%b 
 [[0 1 2]
 [3 4 5]]


In [117]:
# to do a matrix multiplication we do a@b 
# arr shape [a,b] [c,d] b must be equal to c for doing a matrix multiply  and resultant arr will be of shape [a,d]
a = np.arange(6).reshape(3,2)
b = np.arange(7,13).reshape(2,3)
print("matrix multiply a@b \n",a@b) # or a.dot(b)

matrix multiply a@b 
 [[10 11 12]
 [44 49 54]
 [78 87 96]]


In [124]:
# to find min and max from arr just use min and mx functions 
print(arr)
print(arr.min())
print(arr.max())

#print index of max/min number use argmax/argmin
print(arr.argmax())
print(arr.argmin())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
0
49
49
0


In [133]:
# calculating sum
print(arr)
print("\narr sum of each element -",arr.sum()) # or np.sum(arr)
print("\narr sum of each row -",arr.sum(axis=1)) # or np.sum(arr,axis=1)
print("\narr sum of each column -",arr.sum(axis=0)) # or np.sum(arr,axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

arr sum of each element - 1225

arr sum of each row - [ 10  35  60  85 110 135 160 185 210 235]

arr sum of each column - [225 235 245 255 265]


#### Random Function for creating Np array with random values
 * random module of numpy is used to generate various random sequences.
 
 
 * Note: Random.seed() - The numpy random seed is a numerical value that generates a new set or repeats pseudo-random numbers. The value in the numpy random seed saves the state of randomness. If we call the seed function using value 1 multiple times, the computer displays the same random numbers

###### Rand(), randInt(), randn()
* np.rand() - rand() takes shape of array as arguments and returns numbers between 0-1

</br>

* np.randn() -randn() is used to simulate standard normal distribution.takes shape of array as arguments and returns numbers between 0-1

</br>

* np.randint() - np.random.randint returns a random numpy array or scalar, whose element(s) is int, drawn randomly from low (inclusive) to the high (exclusive) range.\
    Syntax\
    np.random.randint(low, high=None, size=None, dtype=’l’)

In [7]:
# setting seed 
np.random.seed(7)

# creating random array of 5 numbers using random.rand - rand() returns numbers between 0-1 
arr = np.random.rand(5)
print(arr)

# 2D Array  
array = np.random.rand(3, 4)
print(array)

[0.07630829 0.77991879 0.43840923 0.72346518 0.97798951]
[[0.53849587 0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904 0.38094113]
 [0.06593635 0.2881456  0.90959353 0.21338535]]


In [19]:
# Standard normal distribution
# setting seed 
np.random.seed(7)
arr = np.random.randn(5) 
print(arr)

# 2D
arr = np.random.randn(3,5)
print("\n random normal distribution of (3,5) shape \n",arr)

# normal distribution with mean 10 and sd 2
x = 10 + 2*np.random.randn(3)
print("\n random normal distribution with mean 10 and sd 2 \n",x)

# same example using normal ()
# syntx = np.random.normal(loc=0.0, scale=1.0, size=None) where loc = mean, and scale = sd
# arr = np.random.normal(10,2,(3,2))

[ 1.6905257  -0.46593737  0.03282016  0.40751628 -0.78892303]

 random normal distribution of (3,5) shape 
 [[ 2.06557291e-03 -8.90385858e-04 -1.75472431e+00  1.01765801e+00
   6.00498516e-01]
 [-6.25428974e-01 -1.71548261e-01  5.05299374e-01 -2.61356415e-01
  -2.42749079e-01]
 [-1.45324141e+00  5.54580312e-01  1.23880905e-01  2.74459924e-01
  -1.52652453e+00]]

 random normal distribution with mean 10 and sd 2 
 [13.30139938 10.30867107  9.22572011]


In [26]:
# Randint()
# np.randint() - np.random.randint returns a random numpy array or scalar, whose element(s) is int, drawn randomly from low (inclusive) to the high (exclusive) range.
# Syntax - np.random.randint(low, high=None, size=None, dtype=’l’)
arr = np.random.randint(1,10,(2,2))
arr

array([[1, 6],
       [5, 4]])

* Random.choice() - np.random.choice returns a numpy array or a scalar by drawing random samples from a given 1-D array

Syntax

np.random.choice(a, size=None, replace=True, p=None)

* where a = 1-D array-like tuple/list/int to choose from

In [29]:
# choice example
arr = np.random.choice([2,7,4,1,8],(2,4))
arr

array([[1, 7, 1, 7],
       [7, 7, 4, 1]])